// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "hideAutomaticTags": boolean;
      "selectedLibraryID": number;
      "inspectorOpen": boolean;
      "zettlrCitationFormat": boolean;
      "input": string;
    };
  }
}
